### ISSUE TITLE
Task 1 failed 

### ISSUE THREAD

**Issue by Zhen-Miao** [sqjin/scAI#10]
Hi, I am running the program, but there seems to be an issue... Could you explain why is this?

Error in { : task 1 failed - "std::bad_alloc"

Thanks!

**Comment by sqjin** [comment]
Hi @Zhen-Miao , could you provide more information?  I have no idea where this issue might happens.

**Comment by Zhen-Miao** [comment]
Hi @sqjin, thank you. I am running the program with R version 4.0.2 on the cluster. I was using 3000 top variable genes with 5000 variable peaks. Following your tutorial, I have built the scAI object `scAI_out`. Then I run the main function 

`scAI_outs <- run_scAI(scAI_outs, K = 20, nrun = 1)`

Then it did not respond in 3 hours. I guess this was because I did not configure well the python packages, so I set `do.fast = F`, when this error occurred. 

Please let me know if additional information is needed... Thanks!

Z

![image](https://user-images.githubusercontent.com/39448538/92069849-73083e80-ed78-11ea-8caa-b19660dc14dd.png)

**Comment by sqjin** [comment]
@Zhen-Miao I just google such issue and it seems this is not a special issue given by scAI. Please see [a similar issue here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1404r1.html). I think this is related with the parallel code. We use the following way for parallel: `    # Calculate the number of cores
    numCores <- min(parallel::detectCores(), nrun)
    cl <- tryCatch({
        parallel::makeForkCluster(numCores)
    }, error = function(e) {
        parallel::makeCluster(numCores)
    })
    doParallel::registerDoParallel(cl)` 
Therefore, you can test whether such parallel works on your cluster.  You can also run your code on your local computer to see whether this issue happens again.

**Comment by Zhen-Miao** [comment]
@sqjin Thank you very much! I will check how this parallel computing can be achieved in my cluster.
