### ISSUE TITLE
Error when following the walkthrough with kidney dataset

### ISSUE THREAD

**Issue by Van1yu3** [sqjin/scAI#5]
Hello! Thank you for proposing the scAI method together with the code and walkthrough.

When following [the walkthrough with kidney dataset](https://htmlpreview.github.io/?https://github.com/sqjin/scAI/blob/master/examples/walkthrough_Kidneydataset.html), I got an error. 

The code I ran is as follows, almost the same as the walkthrough, except that the name of the data in the walkthrough is 'data_kidney.rds'. 

```
 load("data_kidney.RData")
 X <- data_kidney$data # List of data matrix
 labels <- data_kidney$labels # the prior labels of cells, which is used for validation
 init <- data_kidney$init # for reproduction
 scAI_outs <- create_scAIobject(raw.data = X, do.sparse = F)
 scAI_outs <- preprocessing(scAI_outs, assay = NULL)
 scAI_outs <- addpData(scAI_outs, pdata = labels, pdata.name = "Cell types")
 scAI_outs <- run_scAI(scAI_outs, K = 20, nrun = 1, init = init)
```
The error message is 
> Error in { : task 1 failed - "argument to 'which' is not logical"

And the `traceback()` function gives the following message:
> 4: stop(simpleError(msg, call = expr))
> 3: e$fun(obj, substitute(ex), parent.frame(), e$data)
> 2: foreach(i = 1:nrun, .packages = c("Matrix")) %dopar% {
>        set.seed(rand.seed + i - 1)
>        scAImodel(X1, X2, K = K, s = s, alpha = alpha, lambda = lambda,
>            gamma = gamma, maxIter = maxIter, stop_rule = stop_rule,
>            R.init = R.init, W1.init = W1.init, W2.init = W2.init,
>            H.init = H.init, Z.init = Z.init)
>    }
> 1: run_scAI(scAI_outs, K = 20, nrun = 1, init = init)
> 

I wonder if there's some typo in the walkthrough or in the `run_scAI` function?

Thank you!

**Comment by sqjin** [comment]
@Van1yu3  Hello! Thank you for your interest in our work.  I will check this issue. I am wondering whether you have tried other examples?

**Comment by Van1yu3** [comment]
@sqjin Yes, I have tried the walkthrough of the A549 dataset, and it reports no error.
