### ISSUE TITLE
"invalid ELF header" in centos7

### ISSUE THREAD

**Issue by oyxf** [sqjin/scAI#6]
Hi,

I am having some trouble installing the scAI package.

When I try install scAI through download compressed file:scAI-1.0.0.tar.gz,  by : 
install.packages("scAI-1.0.0.tar.gz")

I run into error stating,

* installing *source* package ‘scAI’ ...
** using staged installation
** libs
make: Nothing to be done for 'all'.
installing to /home/liaoke /anaconda3/envs/py37/lib/R/library/00LOCK-scAI-1.0.0/00new/scAI/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘scAI’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/liaoke /anaconda3/envs/py37/lib/R/library/00LOCK-scAI-1.0.0/00new/scAI/libs/scAI.so':
  /home/liaoke /anaconda3/envs/py37/lib/R/library/00LOCK-scAI-1.0.0/00new/scAI/libs/scAI.so: invalid ELF header
Error: loading failed
Execution halted
ERROR: loading failed

Would you have any recommendations as to how to solve this issue?

Thank you!

**Comment by sqjin** [comment]
@oyxf Hello! Have you tried to install it using devtools::install_github("sqjin/scAI")

**Comment by oyxf** [comment]
@sqjin Yes, I have tried. But the network  is not good,  this package  can't be downloaded. 
""
Downloading GitHub repo sqjin/scAI@master
""
So I downloaded the compressed  package file and tried to install it by the function:install.packages().

**Comment by sqjin** [comment]
@oyxf Please check the updated README file, where I added the description of installing from R source codes.

**Comment by oyxf** [comment]
@sqjin Thank you ,it works!
