### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by xuebaliang** [sqjin/scAI#7]
ERROR: dependencies ‘rfunctions’, ‘NNLM’, ‘swne’, ‘circlize’, ‘ComplexHeatmap’, ‘bedr’, ‘biomaRt’ are not available for package ‘scAI’.
Hello, above is the error information when I install "scAI" on the linux server. However, I find that it seems that "rfunction" and "NNLM" do not exist on the internet. Besides, other packages are not easy to install on the linux server, especially for like "install_github(***)". Thus can you solve these problems?

**Comment by sqjin** [comment]
@xuebaliang Hello, I did not test the package on linux server, but here are some suggestions. Can you please manually install these dependences using [install_github(***)?](http://devtools.r-lib.org/reference/install_github) ?  I just checked "rfunction" and "NNLM", and both of them can be found on the github. Please check README file for the link and the way of manually installing these packages.  Please let me know if it works.

**Comment by xuebaliang** [comment]
Thanks for your reply. When I install them on my windows computer, I still have some trouble in packages "swne" and "ComplexHeatmap". The error is
Error: Failed to install 'unknown package' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
Are them really non-existent? Or is it my computer configuration problem?

**Comment by sqjin** [comment]
@xuebaliang Here are the link of these two packages: swne[https://github.com/yanwu2014/swne](url) and ComplexHeatmap[https://github.com/jokergoo/ComplexHeatmap](url). The installation method is the same as we described in the README file of our scAI package.

**Comment by xuebaliang** [comment]
Thanks for your reply. Yes, at first I also found out them. Thus I am very confused about this error. Maybe my computer meets some trouble.

**Comment by sqjin** [comment]
@xuebaliang Can you try "devtools::install_github("sqjin/swne")" and BiocManager::install("ComplexHeatmap") ?

**Comment by xuebaliang** [comment]
Do you have these packages stored in tar.gz? Maybe I can install them offline.

**Comment by sqjin** [comment]
@xuebaliang Yes, you can find it in the main folder. BTY, you also need to install these dependences first.

**Comment by xuebaliang** [comment]
Yes, your package is stored in tar.gz. But these dependences packages do not stored in tar.gz.

**Comment by sqjin** [comment]
I see. But if you want to get the source codes of these packages, you can directly download them from their github. Is it the same error when you try "devtools::install_github("sqjin/swne")" and BiocManager::install("ComplexHeatmap") ?

**Comment by xuebaliang** [comment]
Specially, I try them again just now on windows. The latter "BiocManager::install("ComplexHeatmap")" succeed but the former fail. I get the same error.

**Comment by xuebaliang** [comment]
I download these dependences packages from github, it is .zip form. I will unpack them first and then use "tar -zcvf  file.tar.gz file", for example, "tar -zcvf  swne.tar.gz swne-master". And then I use "R CMD INSTALL swne.tar.gz". Do you think I can succeed?

**Comment by sqjin** [comment]
It looks good. You can also try: 1) Unpack the file and double click .Rproj file 2) In the Rstudio, you then can build this package by cmd+B. You can check how to build package in windows

**Comment by xuebaliang** [comment]
I see. However, they failed. Thus I asked their authors to supply these offline packages ".tar.gz" just now. If I succeed, I will tell you. Thanks for your reply!
