### ISSUE TITLE
10x single cell RNA seq and scATAC seq integration

### ISSUE THREAD

**Issue by ankushs0128** [sqjin/scAI#8]
Is there a easier way to import 10x scRNAseq and scATAC sea data into create_scAIobject?  Is there a walkthrough using 10x genomics data?

**Comment by sqjin** [comment]
> Is there a easier way to import 10x scRNAseq and scATAC sea data into create_scAIobject? Is there a walkthrough using 10x genomics data?
Hello! Sorry for the late reply. The inputs of create_scAIobject are two data matrix. We did not have functions to connect it with 10X genomics data for now. I would suggest to use other tools for generating the required data matrix. Thanks!
